baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Pawan Acharya'
subtitle = 'Aspiring Software Engineer'
theme = 'smol'

[params]
  author = "xyzeep"
  subtitle = "Aspiring Software Engineer"
  dateFmt = "2 January 2006"
  logo = "logo.jpeg"